AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: My SAM Application

Resources:
  MySESFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: app.handler
      Runtime: nodejs18.x
      Timeout: 100
